apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-telegnotify
  labels:
    app: api-telegnotify
    type: gogin 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-telegnotify
      type: gogin
  template:
    metadata:
      name: pod-telegnotify
      labels:
        app: api-telegnotify
        type: gogin
    spec:
      containers:
        - name: ctn-gin
          image: kneerunjun/telegnotify:v0.0.0
          #  DEVICEREG_URL: ${{vars.DEVICEREG_URL}}
          # BOT_BASEURL: ${{ vars.BOT_BASEURL }}
          # BOT_UNAME: ${{ vars.BOT_UNAME }}
          # BOT_TOK: ${{ secrets.BOT_TOK }}
          env:
            - name: BOT_BASEURL
              value: ${{ vars.BOT_BASEURL }}

            - name: BOT_UNAME
              value: ${{ vars.BOT_UNAME }}
            
            - name: DEVICEREG_URL
              value: ${{ vars.DEVICEREG_URL }}

            - name: FLOG
              value: ${{ vars.FLOG }}
            
            - name: SILENT
              value: ${{ SILENT }}
            
            - name: BOT_TOK
              value: ${{ secrets.BOT_TOK }}

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          stdin: true
          tty: true

