name: Linting 

on:
  push:
    branches:
      - v.nightly.0

jobs:
  go-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/go-setup@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: codelint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
