name: TelegNotify-Pipe

on:
  push:
    branches:
      - v.nightly.0
jobs:
  integ_testing:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DEVICEREG_URL: ${{vars.DEVICEREG_URL}}
      BOT_BASEURL: ${{ vars.BOT_BASEURL }}
      BOT_UNAME: ${{ vars.BOT_UNAME }}
      BOT_TOK: ${{ secrets.BOT_TOK }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: local gin server
        run: |
          nohup go run main.go&
          echo "gin server now running .."
      - name: api_tests
        run: |
            go clean --testcache 
            go test -v -timeout 30s -run TestTelegGetMe
            go test -v -timeout 30s -run TestApi
