name: Unit Test 

on:
  push:
    branches:
      - v.nightly.0
# env:
    
# #     - BOT_BASEURL:${{ vars.BOT_BASEURL }}
# #     - BOT_UNAME=${{ vars.BOT_UNAME }}
# #     - BOT_TOK=${{ vars.BOT_TOK }}
jobs:
  unittesting:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: unittests
        run: |
            echo "${{vars.DEVICEREG_URL}}"
            go clean --testcache 
            go test -v -timeout 30s -run TestTelegGetMe
