name: Unit Test 

on:
  push:
    branches:
      - v.nightly.0
jobs:
  unittesting:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: unittests
        env:
          DEVICEREG_URL: ${{vars.DEVICEREG_URL}}
          BOT_BASEURL: ${{ vars.BOT_BASEURL }}
          BOT_UNAME: ${{ vars.BOT_UNAME }}
          BOT_TOK: ${{ secrets.BOT_TOK }}
        run: |
            echo $DEVICEREG_URL
            echo $BOT_BASEURL
            echo $BOT_UNAME
            echo $BOT_TOK
            go clean --testcache 
            go test -v -timeout 30s -run TestTelegGetMe
