name: Unit Test 

on:
  push:
    branches:
      - v.nightly.0

jobs:
  unittesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: unittests
        run: |
            export DEVICEREG_URL=${{ vars.DEVICEREG_URL }}
            export BOT_BASEURL=${{ vars.BOT_BASEURL }}
            export BOT_UNAME=${{ vars.BOT_UNAME }}
            export BOT_TOK=${{ vars.BOT_TOK }}
            go clean --testcache 
            go test -v -timeout 30s -run TestTelegGetMe
