name: Unit Test 

on:
  push:
    branches:
      - v.nightly.0

jobs:
  go-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.22.3'
      - name: unittests
        run: |
            go clean --testcache 
            go test -v -timeout 30s -run TestTelegGetMe
